cask "orca-linux" do
  arch arm: "-arm64"

  version "1.4.188"
  sha256 arm64_linux:  "edb96cf68e4c5d9442b913e82cad5b6c23a6399f8398e8f4798955bbb9c94918",
         x86_64_linux: "2e70cb5e199741e5602a7060825575319f5e03bc2faa4b89cd27328f3f55d4b4"

  url "https://github.com/stablyai/orca/releases/download/v#{version}/orca-linux#{arch}.AppImage"
  name "Orca"
  desc "IDE for orchestrating AI coding agents across terminals and worktrees"
  homepage "https://onorca.dev/"

  livecheck do
    url :url
    strategy :github_latest
  end

  # Why: electron-updater (src/main/updater.ts) handles in-place updates the
  # same way it does on macOS, this time rewriting the AppImage itself. That
  # keeps `brew upgrade` a no-op unless --greedy, matching the upstream cask.
  auto_updates true
  depends_on :linux

  app_image "orca-linux#{arch}.AppImage", target: "Orca.AppImage"
  # Why: a stable, arch-independent launch path. app_image moves the real
  # AppImage to ~/Applications/Orca.AppImage on every (re)install, so this
  # symlink survives upgrades even though the versioned Caskroom path behind
  # it doesn't. install-steps blocks may only contain literal step calls - no
  # interpolated Ruby - so `{{HOMEBREW_PREFIX}}` (a supported template token)
  # is the only way to embed an absolute launch path in the .desktop file
  # below; `#{Dir.home}` isn't available there the way it is here.
  binary "#{Dir.home}/Applications/Orca.AppImage", target: "orca"

  # Why: app_image only moves the AppImage into ~/Applications - unlike macOS
  # Cask, brew's Linux app_image stanza has no Launch Services equivalent, so
  # nothing registers a menu entry or icon on its own. Unlike kitty/warp (real
  # archives Cask auto-unpacks, so their artifact stanzas just point at files
  # already on disk), an AppImage stays one opaque file - its icon has to be
  # pulled out via its own --appimage-extract fallback (no FUSE/root needed)
  # before it can be referenced. This block's default base is :staged_path,
  # so chdir "." and the copy source below land in/read from the version-
  # scoped Caskroom directory, not $HOME.
  #
  # Why the extraction is now full (no icon-only pattern) and kept instead of
  # removed: Orca's own CLI registration (Settings -> Install CLI) writes
  # ~/.local/bin/orca-ide as a bash script with an absolute, version-pinned
  # path to *this* staged AppImage baked in - it can't be pointed at
  # ~/Applications/Orca.AppImage instead, and its generator lives inside
  # Orca's closed-source app.asar, not here. On a host with no usable FUSE
  # device, mounting that AppImage fails ("Cannot mount AppImage, please
  # check your FUSE setup."), and `--appimage-extract-and-run` alone
  # re-extracts and prints the whole file listing to stdout on *every*
  # invocation, corrupting CLI output. So this extracts once, here, next to
  # $APPIMAGE; orca-ide is hand-patched (not generated by this cask, since
  # that generator is closed-source) to run squashfs-root/orca-ide directly
  # when present, falling back to --appimage-extract-and-run otherwise.
  # Keying this to staged_path means brew prunes it for free when a
  # version's Caskroom directory goes away on uninstall/upgrade, and a
  # reinstall regenerates it.
  postflight_steps do
    run "Applications/Orca.AppImage",
        base:  :home,
        args:  ["--appimage-extract"],
        chdir: "."

    copy "squashfs-root/usr/share/icons/hicolor/512x512/apps/orca-ide.png",
         ".local/share/icons/hicolor/512x512/apps/orca.png",
         target_base: :home

    write_file ".local/share/applications/orca.desktop", <<~DESKTOP, base: :home
      [Desktop Entry]
      Version=1.0
      Type=Application
      Name=Orca
      Comment=IDE for orchestrating AI coding agents across terminals and worktrees
      Exec="{{HOMEBREW_PREFIX}}/bin/orca" %U
      Icon=orca
      Categories=Development;
      StartupNotify=true
      StartupWMClass=orca
      Keywords=ai;coding;agent;claude;codex;
    DESKTOP
  end

  uninstall_postflight_steps do
    remove ".local/share/applications/orca.desktop", base: :home
    remove ".local/share/icons/hicolor/512x512/apps/orca.png", base: :home
  end

  # Why: mirrors the upstream cask's zap list. Orca writes worktree/agent
  # state under ~/.orca regardless of platform; ~/.config and ~/.cache are
  # Electron's standard Linux userData/cache dirs (the counterparts to
  # ~/Library/Application Support and ~/Library/Caches on macOS).
  zap trash: [
    "~/.cache/Orca",
    "~/.config/Orca",
    "~/.orca",
  ]
end
