name: Update formulae

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  bump-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get formulae and casks
        id: packages
        run: |
          formulae=$(find Formula -maxdepth 1 -name '*.rb' | sed 's|.*/||; s|\.rb$||' | tr '\n' ' ' | xargs)
          casks=$(find Casks -maxdepth 1 -name '*.rb' | sed 's|.*/||; s|\.rb$||' | tr '\n' ' ' | xargs)
          echo "formulae=$formulae" >> "$GITHUB_OUTPUT"
          echo "casks=$casks" >> "$GITHUB_OUTPUT"

      - name: Bump packages
        uses: Homebrew/actions/bump-packages@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          formulae: ${{ steps.packages.outputs.formulae }}
          casks: kitty-linux