name: Update formulae

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  bump-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get formulae
        id: formulae
        run: echo "list=$(ls -1 Formula/*.rb 2>/dev/null | xargs -I{} basename {} .rb | tr '\n' ' ')" >> "$GITHUB_OUTPUT"

      - name: Get casks
        id: casks
        run: echo "list=$(ls -1 Casks/*.rb 2>/dev/null | xargs -I{} basename {} .rb | tr '\n' ' ')" >> "$GITHUB_OUTPUT"

      - name: Bump packages
        uses: Homebrew/actions/bump-packages@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          formulae: ${{ steps.formulae.outputs.list }}
          casks: ${{ steps.casks.outputs.list }}
